//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobilePro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class security_RolePages
    {
        public int RoleID { get; set; }
        public int PageID { get; set; }
        public Nullable<short> IsHomePage { get; set; }
    }
}
