//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobilePro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class security_Pages
    {
        public int PageID { get; set; }
        public Nullable<int> PageParentID { get; set; }
        public string PageName { get; set; }
        public string Description { get; set; }
        public string PageURL { get; set; }
        public Nullable<int> PageOrdinal { get; set; }
        public Nullable<short> IsMenu { get; set; }
    }
}
