//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobilePro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceBill_VeeraSamy
    {
        public string ReceiptNo { get; set; }
        public string CustomerName { get; set; }
        public string ContactNo { get; set; }
        public string ModelNo { get; set; }
        public string NatureFault { get; set; }
        public string ProblemDesc { get; set; }
        public Nullable<int> StatusCode { get; set; }
        public string TechRemark { get; set; }
        public Nullable<decimal> AdvanceAmount { get; set; }
        public string PaymentType { get; set; }
        public string PasswordType { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> ServiceDate { get; set; }
        public string NRICNo { get; set; }
        public Nullable<int> BrandCode { get; set; }
        public Nullable<int> ColorCode { get; set; }
        public string TechnicianName { get; set; }
        public string IMEINo { get; set; }
        public Nullable<int> OutSourceCode { get; set; }
        public Nullable<decimal> GSTAmount { get; set; }
        public Nullable<decimal> EstimateAmount { get; set; }
        public Nullable<decimal> DiscountAmount { get; set; }
        public Nullable<decimal> NetAmount { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> ReadyBy { get; set; }
        public Nullable<System.DateTime> ReadyDate { get; set; }
        public Nullable<decimal> ActualCost { get; set; }
    }
}
